[package]
name = "mlcs"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
criterion = { version = "0.4", features = ["html_reports"] }

[[bench]]
name = "bench"
harness = false
path = "src/bench.rs"

[dependencies]
priority-queue = "2.0.2"
